-- FASE 1: novas migrations (employees, onboarding, company/employee RPCs, api view).
-- Colar de uma vez no SQL Editor do projeto epi-dev.

-- ============================================================
-- 20260831150000_employees.sql
-- ============================================================
-- FASE 1: employees. See docs/architecture.md §6.1 for the field rationale.
--
-- CPF handling: cpf_hash (HMAC-SHA256) is computed in the APPLICATION layer
-- (src/lib/crypto/cpf-secrets.ts), never in SQL -- the pepper deliberately lives outside
-- Supabase Vault, so raw CPF digits never cross into Postgres at all, only the hash and
-- the AES-256-GCM ciphertext. cpf_masked is a generated column computed from cpf_hash's
-- sibling plaintext-derived input... except we never HAVE the plaintext in Postgres, so
-- masking is also computed app-side and passed in, not generated by the database. See the
-- `cpf_masked` column below for why it is a plain column, not `GENERATED ALWAYS AS`.

create table app.employees (
  id                  uuid primary key default gen_random_uuid(),
  organization_id     uuid not null,
  company_id          uuid not null,
  cpf_hash            bytea not null check (octet_length(cpf_hash) = 32),
  cpf_enc             bytea not null check (octet_length(cpf_enc) >= 29), -- iv(12)+tag(16)+>=1 byte ciphertext
  cpf_masked          text not null check (cpf_masked ~ '^\*{3}\.\d{3}\.\d{3}-\*{2}$'),
  full_name           text not null check (length(btrim(full_name)) between 2 and 150),
  registration_number text check (length(registration_number) <= 40),
  phone_e164          text check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  email               extensions.citext,
  position_title      text check (length(position_title) <= 120),
  department          text check (length(department) <= 120),
  status              text not null default 'ACTIVE' check (status in ('ACTIVE', 'ON_LEAVE', 'TERMINATED')),
  terminated_on        date,
  data_origin         app.data_origin not null default 'MANUAL',
  external_source     text,
  external_ref        text,
  archived_at         timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  created_by          uuid references app.users (id),
  foreign key (organization_id, company_id) references app.companies (organization_id, id) on delete restrict,
  constraint employees_id_company_key unique (id, company_id),
  constraint employees_terminated_ck check ((status = 'TERMINATED') = (terminated_on is not null))
);

comment on table app.employees is
  'A worker of exactly one company. NOT an auth user -- no user_id column exists or ever will (docs/architecture.md §3). Full CPF never stored in plaintext: cpf_hash (HMAC) for dedupe, cpf_enc (AES-256-GCM) for a future permissioned reveal (not built in FASE 1), cpf_masked for display.';
comment on column app.employees.cpf_masked is
  'Plain column, not GENERATED ALWAYS -- there is no plaintext CPF anywhere in Postgres to derive it from (the mask is computed app-side alongside cpf_hash/cpf_enc, from the same plaintext, before any of the three ever reach the database).';

-- One live (non-archived) employee per CPF per company. Two different companies may
-- legitimately share a CPF hash (the same human employed by two client companies of the
-- same partner clinic) -- see docs/architecture.md §3, "no global persons table".
create unique index employees_company_cpf_key on app.employees (company_id, cpf_hash) where archived_at is null;
create unique index employees_external_key on app.employees (company_id, external_source, external_ref)
  where external_ref is not null;
create index employees_company_idx on app.employees (company_id) where archived_at is null;
create index employees_company_dept_idx on app.employees (company_id, department) where archived_at is null and status = 'ACTIVE';
create index employees_name_trgm on app.employees using gin (full_name extensions.gin_trgm_ops);

create trigger employees_set_updated_at
  before update on app.employees
  for each row execute function extensions.moddatetime(updated_at);

alter table app.employees enable row level security;
alter table app.employees force row level security;

grant select on app.employees to authenticated;

create policy employees_select on app.employees
  for select to authenticated
  using (company_id = any ((select auth_ctx.company_ids('employee.read'))::uuid[]));

-- No direct insert/update/delete grant for `authenticated`: all writes go through the
-- api.create_employee / api.update_employee / api.import_employees_commit RPCs (this
-- migration set, below), which enforce permission checks and never accept raw CPF.
revoke insert, update, delete on app.employees from authenticated;

-- ============================================================
-- 20260831150100_onboarding_and_company_rpcs.sql
-- ============================================================
-- FASE 1: organization/company creation RPCs. Both were deliberately deferred out of
-- FASE 0 (docs/architecture.md §7: "organizations are created by a platform/onboarding
-- SECURITY DEFINER RPC") -- this is that RPC, now that there is an actual UI to call it.

-- A brand-new user with ZERO live memberships creates their own DIRECT organization plus
-- its one company, and becomes ORG_ADMIN, in one transaction. This is what makes
-- "Admin cria empresa" (Definition of Done step 1) meaningful without an invite system --
-- see mvp-roadmap.md FASE 1. A user who already has a membership cannot call this again:
-- self-serve onboarding is a one-time bootstrap, not a general "create another org" tool
-- (that path, for a PARTNER admin adding a second organization, doesn't exist yet and
-- isn't needed yet -- flagged, not built speculatively).
create function api.onboard_organization(
  p_org_legal_name text,
  p_org_cnpj text,
  p_company_legal_name text,
  p_company_cnpj text,
  p_company_trade_name text default null
)
returns table (organization_id uuid, company_id uuid)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_org_id uuid;
  v_company_id uuid;
begin
  if v_uid is null then
    raise exception 'not_authenticated' using errcode = '28000';
  end if;

  if exists (select 1 from authz.memberships m where m.user_id = v_uid and m.revoked_at is null) then
    raise exception 'already_onboarded' using errcode = '42710';
  end if;

  insert into app.organizations (kind, legal_name, cnpj)
  values ('DIRECT', p_org_legal_name, p_org_cnpj)
  returning id into v_org_id;

  insert into app.companies (organization_id, organization_kind, legal_name, cnpj, trade_name)
  values (v_org_id, 'DIRECT', p_company_legal_name, p_company_cnpj, p_company_trade_name)
  returning id into v_company_id;

  insert into authz.memberships (user_id, organization_id, company_id, role, accepted_at)
  values (v_uid, v_org_id, null, 'ORG_ADMIN', now());

  return query select v_org_id, v_company_id;
end;
$$;

comment on function api.onboard_organization(text, text, text, text, text) is
  'Self-serve bootstrap: a user with zero memberships creates their own DIRECT organization + its one company + becomes ORG_ADMIN. One-shot -- rejects a second call once any membership exists.';

revoke execute on function api.onboard_organization(text, text, text, text, text) from public, anon;
grant execute on function api.onboard_organization(text, text, text, text, text) to authenticated;

-- Adding a further company (a PARTNER organization's second, third, ... client company).
-- Requires org-wide ORG_ADMIN -- a company-scoped membership cannot create sibling
-- companies. For a DIRECT organization this will always fail past the first company: the
-- `companies_one_per_direct_org` unique index (FASE 0) rejects it at the constraint layer,
-- which is the correct enforcement point, not a check duplicated here.
create function api.create_company(
  p_organization_id uuid,
  p_legal_name text,
  p_cnpj text,
  p_trade_name text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_uid uuid := (select auth.uid());
  v_company_id uuid;
  v_org_kind app.org_kind;
begin
  if not exists (
    select 1 from authz.memberships m
    where m.user_id = v_uid and m.organization_id = p_organization_id
      and m.company_id is null and m.role = 'ORG_ADMIN' and m.revoked_at is null
  ) then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;

  select kind into v_org_kind from app.organizations where id = p_organization_id;

  insert into app.companies (organization_id, organization_kind, legal_name, cnpj, trade_name)
  values (p_organization_id, v_org_kind, p_legal_name, p_cnpj, p_trade_name)
  returning id into v_company_id;

  return v_company_id;
end;
$$;

comment on function api.create_company(uuid, text, text, text) is
  'Adds a company to an existing organization. Requires org-wide ORG_ADMIN. A DIRECT organization can never end up with a second company -- enforced by the companies_one_per_direct_org unique index, not duplicated here.';

revoke execute on function api.create_company(uuid, text, text, text) from public, anon;
grant execute on function api.create_company(uuid, text, text, text) to authenticated;

-- Update an existing company's editable fields. Full CNPJ/organization re-parenting are
-- deliberately not exposed here -- see docs/architecture.md §3, "re-parenting is not a
-- supported operation".
create function api.update_company(
  p_company_id uuid,
  p_legal_name text,
  p_trade_name text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if not (select auth_ctx.has_permission(p_company_id, 'company.settings.update')) then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;

  update app.companies
  set legal_name = p_legal_name, trade_name = p_trade_name
  where id = p_company_id;

  if not found then
    raise exception 'not_found' using errcode = 'P0002';
  end if;
end;
$$;

comment on function api.update_company(uuid, text, text) is
  'Updates legal_name/trade_name only. CNPJ and organization_id are immutable through this RPC -- see docs/architecture.md §3.';

revoke execute on function api.update_company(uuid, text, text) from public, anon;
grant execute on function api.update_company(uuid, text, text) to authenticated;

-- ============================================================
-- 20260831150200_employee_rpcs.sql
-- ============================================================
-- FASE 1: employee create/update/import RPCs.
--
-- CPF hash/ciphertext parameters are accepted as base64 TEXT, not `bytea` directly: a
-- PostgREST JSON-RPC call would have to send Postgres's own hex-text bytea format
-- (`\x...`) to bind a bytea parameter correctly, which is a needless coupling to a
-- Postgres-internal wire detail. Every RPC below takes `_b64` text parameters and decodes
-- with `decode(x, 'base64')` -- simple, unambiguous, and exactly what
-- src/lib/crypto/cpf-secrets.ts already emits (Buffer -> base64 string).

create function api.create_employee(
  p_company_id uuid,
  p_full_name text,
  p_cpf_hash_b64 text,
  p_cpf_enc_b64 text,
  p_cpf_masked text,
  p_registration_number text default null,
  p_phone_e164 text default null,
  p_email text default null,
  p_position_title text default null,
  p_department text default null,
  p_data_origin app.data_origin default 'MANUAL',
  p_external_source text default null,
  p_external_ref text default null
)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_org_id uuid;
  v_employee_id uuid;
begin
  if not (select auth_ctx.has_permission(p_company_id, 'employee.create')) then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;

  select organization_id into v_org_id from app.companies where id = p_company_id;

  insert into app.employees (
    organization_id, company_id, full_name, cpf_hash, cpf_enc, cpf_masked,
    registration_number, phone_e164, email, position_title, department,
    data_origin, external_source, external_ref, created_by
  ) values (
    v_org_id, p_company_id, p_full_name,
    decode(p_cpf_hash_b64, 'base64'), decode(p_cpf_enc_b64, 'base64'), p_cpf_masked,
    p_registration_number, p_phone_e164, p_email, p_position_title, p_department,
    p_data_origin, p_external_source, p_external_ref, (select auth.uid())
  )
  returning id into v_employee_id;

  return v_employee_id;
exception
  when unique_violation then
    raise exception 'cpf_already_registered' using errcode = '23505';
end;
$$;

comment on function api.create_employee(uuid, text, text, text, text, text, text, text, text, text, app.data_origin, text, text) is
  'Manual (or import-row) employee creation. Never accepts a raw CPF -- caller must already have computed cpf_hash/cpf_enc/cpf_masked (src/lib/crypto/cpf-secrets.ts, src/lib/br/cpf.ts) before calling.';

revoke execute on function api.create_employee(uuid, text, text, text, text, text, text, text, text, text, app.data_origin, text, text) from public, anon;
grant execute on function api.create_employee(uuid, text, text, text, text, text, text, text, text, text, app.data_origin, text, text) to authenticated;

create function api.update_employee(
  p_employee_id uuid,
  p_full_name text,
  p_registration_number text,
  p_phone_e164 text,
  p_email text,
  p_position_title text,
  p_department text,
  p_status text
)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_company_id uuid;
begin
  select company_id into v_company_id from app.employees where id = p_employee_id and archived_at is null;
  if v_company_id is null then
    raise exception 'not_found' using errcode = 'P0002';
  end if;

  if not (select auth_ctx.has_permission(v_company_id, 'employee.update')) then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;

  update app.employees set
    full_name = p_full_name,
    registration_number = p_registration_number,
    phone_e164 = p_phone_e164,
    email = p_email,
    position_title = p_position_title,
    department = p_department,
    status = p_status,
    terminated_on = case when p_status = 'TERMINATED' then coalesce(terminated_on, current_date) else null end
  where id = p_employee_id;
end;
$$;

comment on function api.update_employee(uuid, text, text, text, text, text, text, text) is
  'Updates editable employee fields. CPF (hash/enc/masked) is never editable through this RPC -- a CPF correction is a deliberately separate, rarer operation not built in FASE 1.';

revoke execute on function api.update_employee(uuid, text, text, text, text, text, text, text) from public, anon;
grant execute on function api.update_employee(uuid, text, text, text, text, text, text, text) to authenticated;

-- Bulk commit for the CSV import flow (docs/architecture.md §6.4 / mvp-roadmap.md FASE 1).
-- Takes an ALREADY VALIDATED jsonb array -- parsing, column mapping, CPF/phone validation
-- and per-row hashing all happen client/server-side in Next.js before this is called. One
-- statement, one transaction: either the whole batch commits or none of it does. Rows
-- whose (company_id, cpf_hash) already exists are UPDATED (idempotent re-import), not
-- duplicated or rejected -- matches the "upload -> preview -> map -> validate -> confirm"
-- flow allowing a corrected re-upload of the same file.
create function api.import_employees_commit(p_company_id uuid, p_rows jsonb)
returns table (created_count int, updated_count int)
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_org_id uuid;
  v_created int;
  v_updated int;
begin
  if not (select auth_ctx.has_permission(p_company_id, 'employee.import')) then
    raise exception 'insufficient_privilege' using errcode = '42501';
  end if;

  if jsonb_array_length(p_rows) > 20000 then
    raise exception 'batch_too_large' using errcode = '54000';
  end if;

  select organization_id into v_org_id from app.companies where id = p_company_id;

  with incoming as (
    select
      r.full_name,
      decode(r.cpf_hash_b64, 'base64') as cpf_hash,
      decode(r.cpf_enc_b64, 'base64') as cpf_enc,
      r.cpf_masked,
      r.registration_number,
      r.phone_e164,
      r.email,
      r.position_title,
      r.department
    from jsonb_to_recordset(p_rows) as r(
      full_name text, cpf_hash_b64 text, cpf_enc_b64 text, cpf_masked text,
      registration_number text, phone_e164 text, email text,
      position_title text, department text
    )
  ),
  ins as (
    insert into app.employees (
      organization_id, company_id, full_name, cpf_hash, cpf_enc, cpf_masked,
      registration_number, phone_e164, email, position_title, department,
      data_origin, created_by
    )
    select
      v_org_id, p_company_id, i.full_name, i.cpf_hash, i.cpf_enc, i.cpf_masked,
      i.registration_number, i.phone_e164, i.email, i.position_title, i.department,
      'IMPORT', (select auth.uid())
    from incoming i
    on conflict (company_id, cpf_hash) where archived_at is null
    do update set
      full_name = excluded.full_name,
      cpf_enc = excluded.cpf_enc,
      cpf_masked = excluded.cpf_masked,
      registration_number = excluded.registration_number,
      phone_e164 = excluded.phone_e164,
      email = excluded.email,
      position_title = excluded.position_title,
      department = excluded.department
    returning (xmax = 0) as was_insert
  )
  select
    count(*) filter (where was_insert),
    count(*) filter (where not was_insert)
  into v_created, v_updated
  from ins;

  return query select v_created, v_updated;
end;
$$;

comment on function api.import_employees_commit(uuid, jsonb) is
  'Set-based bulk upsert for CSV import, one statement/transaction. Hard cap 20,000 rows per call -- see docs/mvp-roadmap.md FASE 1; the UI must chunk or reject larger files with an honest message, never truncate silently. xmax=0 is the standard Postgres idiom to distinguish an INSERT from an ON CONFLICT UPDATE in the same RETURNING clause.';

revoke execute on function api.import_employees_commit(uuid, jsonb) from public, anon;
grant execute on function api.import_employees_commit(uuid, jsonb) to authenticated;

-- ============================================================
-- 20260831150300_employees_api_view.sql
-- ============================================================
-- FASE 1: expose employees for reading through the curated `api` schema. Writes stay
-- RPC-only (api.create_employee / api.update_employee / api.import_employees_commit) --
-- there is deliberately no INSERT/UPDATE grant on this view, consistent with
-- docs/architecture.md §7: PostgREST direct writes are never how state changes here.
--
-- cpf_hash and cpf_enc are NOT selected -- there is no legitimate reason for the panel to
-- ever receive them over HTTP. Only cpf_masked (display) is exposed.

create view api.employees
  with (security_invoker = true) as
select
  id, organization_id, company_id, full_name, cpf_masked, registration_number,
  phone_e164, email, position_title, department, status, terminated_on,
  data_origin, external_source, external_ref, created_at, updated_at
from app.employees
where archived_at is null;

comment on view api.employees is
  'Read-only projection of app.employees. Never selects cpf_hash/cpf_enc -- cpf_masked is the only CPF representation that ever crosses HTTP. See docs/architecture.md §6/§16.';

grant select on api.employees to authenticated;

