-- FASE 1 Definition of Done: "funcionário criado em um tenant não aparece em nenhuma
-- query do outro (RLS e teste de API)". Exercises the real RPCs (onboard_organization,
-- create_employee, import_employees_commit), not just raw table isolation -- see
-- mvp-roadmap.md FASE 1.

create extension if not exists pgtap with schema extensions;

begin;

select plan(9);

-- Two tenant-admin auth users.
insert into auth.users (
  instance_id, id, aud, role, email, encrypted_password, email_confirmed_at,
  raw_app_meta_data, raw_user_meta_data, created_at, updated_at,
  confirmation_token, recovery_token, email_change_token_new, email_change,
  is_sso_user, is_anonymous
) values
  ('00000000-0000-0000-0000-000000000000', '33333333-3333-3333-3333-333333333301',
   'authenticated', 'authenticated', 'admin-c@tenant-c.test',
   extensions.crypt('x', extensions.gen_salt('bf')), now(),
   '{}', '{"full_name":"Admin C"}', now(), now(), '', '', '', '', false, false),
  ('00000000-0000-0000-0000-000000000000', '44444444-4444-4444-4444-444444444401',
   'authenticated', 'authenticated', 'admin-d@tenant-d.test',
   extensions.crypt('x', extensions.gen_salt('bf')), now(),
   '{}', '{"full_name":"Admin D"}', now(), now(), '', '', '', '', false, false);

-- Scratch table to carry company ids (generated by the RPC, not known up front) across
-- the role-switching statements below -- a plain SQL variable does not survive that.
create temporary table fixture_ids (label text primary key, id uuid not null);
-- The fixture-setup DO blocks below write to this table WHILE impersonating
-- `authenticated` (SET LOCAL ROLE), and a session-temp table created by the superuser/
-- owner grants nothing to other roles by default -- without this, the very first INSERT
-- inside a role-switched DO block fails with "permission denied for table fixture_ids".
grant all on fixture_ids to authenticated;

-- Each tenant bootstraps itself through the real onboarding RPC, exactly like production.
do $$
declare v_company_id uuid;
begin
  set local role authenticated;
  perform set_config('request.jwt.claims', '{"sub":"33333333-3333-3333-3333-333333333301","role":"authenticated"}', true);
  select company_id into v_company_id from api.onboard_organization('Tenant C LTDA', '11222333000181', 'Tenant C LTDA', '11222333000181', null);
  insert into fixture_ids values ('company_c', v_company_id);
  reset role;
end $$;

do $$
declare v_company_id uuid;
begin
  set local role authenticated;
  perform set_config('request.jwt.claims', '{"sub":"44444444-4444-4444-4444-444444444401","role":"authenticated"}', true);
  select company_id into v_company_id from api.onboard_organization('Tenant D LTDA', '22333444000199', 'Tenant D LTDA', '22333444000199', null);
  insert into fixture_ids values ('company_d', v_company_id);
  reset role;
end $$;

select ok(
  (select count(*) = 2 from fixture_ids),
  'both tenants onboarded and each returned a company_id'
);

-- Tenant C creates one employee; tenant D creates a DIFFERENT employee with a DIFFERENT
-- CPF (same-CPF-different-company is a separate, already-covered case -- see the FASE 1
-- RPC smoke test for the same-company duplicate-CPF rejection).
-- extensions.digest/crypt etc. are computed BEFORE `set local role authenticated` --
-- `authenticated` has no USAGE grant on the `extensions` schema at all (by design, see
-- docs/architecture.md §7), so evaluating them as an argument expression AFTER the role
-- switch fails with "permission denied for schema extensions". The owner/superuser
-- context this DO block starts in can resolve them fine; compute-then-switch is required.
do $$
declare v_company_c uuid; v_employee_id uuid; v_cpf_hash_b64 text; v_cpf_enc_b64 text;
begin
  select id into v_company_c from fixture_ids where label = 'company_c';
  v_cpf_hash_b64 := encode(extensions.digest('cpf-c', 'sha256'), 'base64');
  v_cpf_enc_b64 := encode(decode('00000000000000000000000000000000000000000000000000000000', 'hex') || 'fake-c'::bytea, 'base64');

  set local role authenticated;
  perform set_config('request.jwt.claims', '{"sub":"33333333-3333-3333-3333-333333333301","role":"authenticated"}', true);
  select api.create_employee(
    v_company_c, 'Funcionário Tenant C',
    v_cpf_hash_b64, v_cpf_enc_b64,
    '***.111.111-**'
  ) into v_employee_id;
  insert into fixture_ids values ('employee_c', v_employee_id);
  reset role;
end $$;

do $$
declare v_company_d uuid; v_employee_id uuid; v_cpf_hash_b64 text; v_cpf_enc_b64 text;
begin
  select id into v_company_d from fixture_ids where label = 'company_d';
  v_cpf_hash_b64 := encode(extensions.digest('cpf-d', 'sha256'), 'base64');
  v_cpf_enc_b64 := encode(decode('00000000000000000000000000000000000000000000000000000000', 'hex') || 'fake-d'::bytea, 'base64');

  set local role authenticated;
  perform set_config('request.jwt.claims', '{"sub":"44444444-4444-4444-4444-444444444401","role":"authenticated"}', true);
  select api.create_employee(
    v_company_d, 'Funcionário Tenant D',
    v_cpf_hash_b64, v_cpf_enc_b64,
    '***.222.222-**'
  ) into v_employee_id;
  insert into fixture_ids values ('employee_d', v_employee_id);
  reset role;
end $$;

select ok(
  (select count(*) = 2 from fixture_ids where label like 'employee_%'),
  'both tenants created one employee each'
);

-- The actual isolation assertions, as each tenant's user, through api.employees (the same
-- path the real app uses -- not a raw app.employees read).
set local role authenticated;
set local request.jwt.claims = '{"sub":"33333333-3333-3333-3333-333333333301","role":"authenticated"}';

select results_eq(
  $$ select full_name from api.employees $$,
  $$ values ('Funcionário Tenant C'::text) $$,
  'tenant C sees exactly its own employee via api.employees'
);

select is(
  (select count(*)::int from api.employees where id = (select id from fixture_ids where label = 'employee_d')),
  0,
  'tenant C cannot see tenant D''s employee by id, even directly'
);

-- app.employees itself DOES have a SELECT grant to authenticated (docs/architecture.md
-- §7 requires this for the api.* security_invoker views to work) -- so this checks that
-- RLS, not merely the view's own filtering, is what blocks cross-tenant reads even
-- querying the base table directly.
select results_eq(
  $$ select full_name from app.employees $$,
  $$ values ('Funcionário Tenant C'::text) $$,
  'tenant C sees exactly its own employee even querying app.employees directly (RLS, not just the view, is the boundary)'
);

reset role;

set local role authenticated;
set local request.jwt.claims = '{"sub":"44444444-4444-4444-4444-444444444401","role":"authenticated"}';

select results_eq(
  $$ select full_name from api.employees $$,
  $$ values ('Funcionário Tenant D'::text) $$,
  'tenant D sees exactly its own employee via api.employees, never tenant C''s'
);

select throws_ok(
  $$ select api.update_employee(
       (select id from fixture_ids where label = 'employee_c'),
       'Hijacked', null, null, null, null, null, 'ACTIVE'
     ) $$,
  '42501',
  'tenant D cannot update tenant C''s employee via api.update_employee (insufficient_privilege)'
);

reset role;

-- One more cross-check from the SUPERUSER perspective (bypasses RLS, sees ground truth):
-- confirm the attempted hijack from the previous assertion did NOT silently apply before
-- raising -- i.e. the whole RPC call rolled back, not just the final check.
select is(
  (select full_name from app.employees where id = (select id from fixture_ids where label = 'employee_c')),
  'Funcionário Tenant C',
  'the rejected update_employee call left tenant C''s employee name unchanged'
);

select is(
  (select count(*)::int from app.employees),
  2,
  'exactly 2 employees exist in total across both tenants -- no stray rows from any failed attempt'
);

select * from finish();

rollback;
