-- FASE 1: employees. See docs/architecture.md §6.1 for the field rationale.
--
-- CPF handling: cpf_hash (HMAC-SHA256) is computed in the APPLICATION layer
-- (src/lib/crypto/cpf-secrets.ts), never in SQL -- the pepper deliberately lives outside
-- Supabase Vault, so raw CPF digits never cross into Postgres at all, only the hash and
-- the AES-256-GCM ciphertext. cpf_masked is a generated column computed from cpf_hash's
-- sibling plaintext-derived input... except we never HAVE the plaintext in Postgres, so
-- masking is also computed app-side and passed in, not generated by the database. See the
-- `cpf_masked` column below for why it is a plain column, not `GENERATED ALWAYS AS`.

create table app.employees (
  id                  uuid primary key default gen_random_uuid(),
  organization_id     uuid not null,
  company_id          uuid not null,
  cpf_hash            bytea not null check (octet_length(cpf_hash) = 32),
  cpf_enc             bytea not null check (octet_length(cpf_enc) >= 29), -- iv(12)+tag(16)+>=1 byte ciphertext
  cpf_masked          text not null check (cpf_masked ~ '^\*{3}\.\d{3}\.\d{3}-\*{2}$'),
  full_name           text not null check (length(btrim(full_name)) between 2 and 150),
  registration_number text check (length(registration_number) <= 40),
  phone_e164          text check (phone_e164 ~ '^\+[1-9][0-9]{7,14}$'),
  email               extensions.citext,
  position_title      text check (length(position_title) <= 120),
  department          text check (length(department) <= 120),
  status              text not null default 'ACTIVE' check (status in ('ACTIVE', 'ON_LEAVE', 'TERMINATED')),
  terminated_on        date,
  data_origin         app.data_origin not null default 'MANUAL',
  external_source     text,
  external_ref        text,
  archived_at         timestamptz,
  created_at          timestamptz not null default now(),
  updated_at          timestamptz not null default now(),
  created_by          uuid references app.users (id),
  foreign key (organization_id, company_id) references app.companies (organization_id, id) on delete restrict,
  constraint employees_id_company_key unique (id, company_id),
  constraint employees_terminated_ck check ((status = 'TERMINATED') = (terminated_on is not null))
);

comment on table app.employees is
  'A worker of exactly one company. NOT an auth user -- no user_id column exists or ever will (docs/architecture.md §3). Full CPF never stored in plaintext: cpf_hash (HMAC) for dedupe, cpf_enc (AES-256-GCM) for a future permissioned reveal (not built in FASE 1), cpf_masked for display.';
comment on column app.employees.cpf_masked is
  'Plain column, not GENERATED ALWAYS -- there is no plaintext CPF anywhere in Postgres to derive it from (the mask is computed app-side alongside cpf_hash/cpf_enc, from the same plaintext, before any of the three ever reach the database).';

-- One live (non-archived) employee per CPF per company. Two different companies may
-- legitimately share a CPF hash (the same human employed by two client companies of the
-- same partner clinic) -- see docs/architecture.md §3, "no global persons table".
create unique index employees_company_cpf_key on app.employees (company_id, cpf_hash) where archived_at is null;
create unique index employees_external_key on app.employees (company_id, external_source, external_ref)
  where external_ref is not null;
create index employees_company_idx on app.employees (company_id) where archived_at is null;
create index employees_company_dept_idx on app.employees (company_id, department) where archived_at is null and status = 'ACTIVE';
create index employees_name_trgm on app.employees using gin (full_name extensions.gin_trgm_ops);

create trigger employees_set_updated_at
  before update on app.employees
  for each row execute function extensions.moddatetime(updated_at);

alter table app.employees enable row level security;
alter table app.employees force row level security;

grant select on app.employees to authenticated;

create policy employees_select on app.employees
  for select to authenticated
  using (company_id = any ((select auth_ctx.company_ids('employee.read'))::uuid[]));

-- No direct insert/update/delete grant for `authenticated`: all writes go through the
-- api.create_employee / api.update_employee / api.import_employees_commit RPCs (this
-- migration set, below), which enforce permission checks and never accept raw CPF.
revoke insert, update, delete on app.employees from authenticated;
